"""inventory_and_receiving

Revision ID: 99c67baa4a76
Revises: '3a78cc63e38a'
Create Date: 2026-08-13 15:37:06.440938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "99c67baa4a76"
down_revision: Union[str, None] = "3a78cc63e38a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory_reconciliations",
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=True),
        sa.Column(
            "snapshot_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("total_ledger_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_balance_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("variance_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("investigated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investigated_by_user_id"],
            ["users.id"],
            name=op.f("fk_inventory_reconciliations_investigated_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"],
            ["sellers.id"],
            name=op.f("fk_inventory_reconciliations_seller_id_sellers"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_reconciliations_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_reconciliations")),
    )
    op.create_index(
        op.f("ix_inventory_reconciliations_seller_id"),
        "inventory_reconciliations",
        ["seller_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reconciliations_warehouse_id"),
        "inventory_reconciliations",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "receipts",
        sa.Column("receipt_number", sa.String(length=50), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_reference", sa.String(length=255), nullable=False),
        sa.Column("client_draft_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("expected_arrival_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_arrival_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_by_user_id", sa.UUID(), nullable=True),
        sa.Column("completed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_duplicate_override", sa.Boolean(), nullable=False),
        sa.Column("original_receipt_id", sa.UUID(), nullable=True),
        sa.Column("overridden_by_user_id", sa.UUID(), nullable=True),
        sa.Column("override_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_user_id"],
            ["users.id"],
            name=op.f("fk_receipts_completed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["original_receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipts_original_receipt_id_receipts"),
        ),
        sa.ForeignKeyConstraint(
            ["overridden_by_user_id"],
            ["users.id"],
            name=op.f("fk_receipts_overridden_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["sellers.id"], name=op.f("fk_receipts_seller_id_sellers")
        ),
        sa.ForeignKeyConstraint(
            ["started_by_user_id"], ["users.id"], name=op.f("fk_receipts_started_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], name=op.f("fk_receipts_warehouse_id_warehouses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipts")),
        sa.UniqueConstraint("receipt_number", name="uq_receipt_number"),
    )
    op.create_index(
        op.f("ix_receipts_client_draft_id"), "receipts", ["client_draft_id"], unique=True
    )
    op.create_index(
        op.f("ix_receipts_receipt_number"), "receipts", ["receipt_number"], unique=True
    )
    op.create_index(op.f("ix_receipts_seller_id"), "receipts", ["seller_id"], unique=False)
    op.create_index(
        "ix_receipts_seller_wh", "receipts", ["seller_id", "warehouse_id"], unique=False
    )
    op.create_index(
        "ix_receipts_source",
        "receipts",
        ["warehouse_id", "source_type", "source_reference"],
        unique=False,
    )
    op.create_index(op.f("ix_receipts_status"), "receipts", ["status"], unique=False)
    op.create_index(op.f("ix_receipts_warehouse_id"), "receipts", ["warehouse_id"], unique=False)
    op.create_table(
        "inventory_adjustments",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("inventory_state", sa.String(length=50), nullable=False),
        sa.Column("requested_delta", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reason_code", sa.String(length=50), nullable=False),
        sa.Column("reason_text", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_inventory_adjustments_approved_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["warehouse_locations.id"],
            name=op.f("fk_inventory_adjustments_location_id_warehouse_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_adjustments_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_inventory_adjustments_requested_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["sellers.id"], name=op.f("fk_inventory_adjustments_seller_id_sellers")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_adjustments_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_adjustments")),
    )
    op.create_index(
        op.f("ix_inventory_adjustments_product_id"),
        "inventory_adjustments",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_adjustments_seller_id"),
        "inventory_adjustments",
        ["seller_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_adjustments_warehouse_id"),
        "inventory_adjustments",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "inventory_balances",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("inventory_state", sa.String(length=50), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["warehouse_locations.id"],
            name=op.f("fk_inventory_balances_location_id_warehouse_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_inventory_balances_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["sellers.id"], name=op.f("fk_inventory_balances_seller_id_sellers")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_balances_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_balances")),
        sa.UniqueConstraint(
            "seller_id",
            "product_id",
            "warehouse_id",
            "location_id",
            "inventory_state",
            name="uq_balance_composite_scope",
        ),
    )
    op.create_index(
        "ix_balances_wh_product",
        "inventory_balances",
        ["warehouse_id", "product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_balances_inventory_state"),
        "inventory_balances",
        ["inventory_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_balances_location_id"),
        "inventory_balances",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_balances_product_id"),
        "inventory_balances",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_balances_seller_id"), "inventory_balances", ["seller_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_balances_warehouse_id"),
        "inventory_balances",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "inventory_movements",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("inventory_state", sa.String(length=50), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("movement_type", sa.String(length=50), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_line_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("reason_code", sa.String(length=50), nullable=True),
        sa.Column("reason_text", sa.String(length=500), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reversal_of_movement_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_inventory_movements_actor_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["warehouse_locations.id"],
            name=op.f("fk_inventory_movements_location_id_warehouse_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_movements_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_movement_id"],
            ["inventory_movements.id"],
            name=op.f("fk_inventory_movements_reversal_of_movement_id_inventory_movements"),
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["sellers.id"], name=op.f("fk_inventory_movements_seller_id_sellers")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_movements_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
        sa.UniqueConstraint(
            "source_type",
            "source_line_id",
            "movement_type",
            "idempotency_key",
            name="uq_movement_source_retry",
        ),
    )
    op.create_index(
        op.f("ix_inventory_movements_idempotency_key"),
        "inventory_movements",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_inventory_state"),
        "inventory_movements",
        ["inventory_state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_location_id"),
        "inventory_movements",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_movement_type"),
        "inventory_movements",
        ["movement_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_product_id"),
        "inventory_movements",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_seller_id"),
        "inventory_movements",
        ["seller_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_source_id"),
        "inventory_movements",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_source_type"),
        "inventory_movements",
        ["source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_warehouse_id"),
        "inventory_movements",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        "ix_movements_seller_product",
        "inventory_movements",
        ["seller_id", "product_id"],
        unique=False,
    )
    op.create_index(
        "ix_movements_wh_loc", "inventory_movements", ["warehouse_id", "location_id"], unique=False
    )
    op.create_table(
        "receipt_events",
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("details", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_receipt_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_events_receipt_id_receipts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_events")),
    )
    op.create_index(
        op.f("ix_receipt_events_receipt_id"), "receipt_events", ["receipt_id"], unique=False
    )
    op.create_table(
        "receipt_lines",
        sa.Column("receipt_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("expected_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("sellable_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("damaged_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("quarantined_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("shortage_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("overage_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_receipt_lines_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
            name=op.f("fk_receipt_lines_receipt_id_receipts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receipt_lines")),
        sa.UniqueConstraint("receipt_id", "product_id", name="uq_receipt_line_product"),
    )
    op.create_index(
        op.f("ix_receipt_lines_product_id"), "receipt_lines", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_receipt_lines_receipt_id"), "receipt_lines", ["receipt_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipt_lines_receipt_id"), table_name="receipt_lines")
    op.drop_index(op.f("ix_receipt_lines_product_id"), table_name="receipt_lines")
    op.drop_table("receipt_lines")
    op.drop_index(op.f("ix_receipt_events_receipt_id"), table_name="receipt_events")
    op.drop_table("receipt_events")
    op.drop_index("ix_movements_wh_loc", table_name="inventory_movements")
    op.drop_index("ix_movements_seller_product", table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_warehouse_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_source_type"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_source_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_seller_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_product_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_movement_type"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_location_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_inventory_state"), table_name="inventory_movements")
    op.drop_index(op.f("ix_inventory_movements_idempotency_key"), table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index(op.f("ix_inventory_balances_warehouse_id"), table_name="inventory_balances")
    op.drop_index(op.f("ix_inventory_balances_seller_id"), table_name="inventory_balances")
    op.drop_index(op.f("ix_inventory_balances_product_id"), table_name="inventory_balances")
    op.drop_index(op.f("ix_inventory_balances_location_id"), table_name="inventory_balances")
    op.drop_index(op.f("ix_inventory_balances_inventory_state"), table_name="inventory_balances")
    op.drop_index("ix_balances_wh_product", table_name="inventory_balances")
    op.drop_table("inventory_balances")
    op.drop_index(
        op.f("ix_inventory_adjustments_warehouse_id"), table_name="inventory_adjustments"
    )
    op.drop_index(op.f("ix_inventory_adjustments_seller_id"), table_name="inventory_adjustments")
    op.drop_index(op.f("ix_inventory_adjustments_product_id"), table_name="inventory_adjustments")
    op.drop_table("inventory_adjustments")
    op.drop_index(op.f("ix_receipts_warehouse_id"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_status"), table_name="receipts")
    op.drop_index("ix_receipts_source", table_name="receipts")
    op.drop_index("ix_receipts_seller_wh", table_name="receipts")
    op.drop_index(op.f("ix_receipts_seller_id"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_receipt_number"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_client_draft_id"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(
        op.f("ix_inventory_reconciliations_warehouse_id"), table_name="inventory_reconciliations"
    )
    op.drop_index(
        op.f("ix_inventory_reconciliations_seller_id"), table_name="inventory_reconciliations"
    )
    op.drop_table("inventory_reconciliations")
    # ### end Alembic commands ###
