"""orders_and_fulfillment

Revision ID: c9a20c29ffff
Revises: '99c67baa4a76'
Create Date: 2026-08-13 15:49:27.363479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c9a20c29ffff"
down_revision: Union[str, None] = "99c67baa4a76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("seller_order_number", sa.String(length=100), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("policy_snapshot", sa.JSON(), nullable=True),
        sa.Column("customer_name", sa.String(length=200), nullable=True),
        sa.Column("shipping_address_line1", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=30), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["sellers.id"], name=op.f("fk_orders_seller_id_sellers")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], name=op.f("fk_orders_warehouse_id_warehouses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("seller_id", "seller_order_number", name="uq_seller_order_number"),
    )
    op.create_index(op.f("ix_orders_seller_id"), "orders", ["seller_id"], unique=False)
    op.create_index(
        op.f("ix_orders_seller_order_number"), "orders", ["seller_order_number"], unique=False
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_warehouse_id"), "orders", ["warehouse_id"], unique=False)
    op.create_index("ix_orders_wh_status", "orders", ["warehouse_id", "status"], unique=False)
    op.create_table(
        "order_lines",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("ordered_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reserved_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("picked_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("shipped_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("backordered_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cancelled_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_lines_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_order_lines_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
        sa.UniqueConstraint("order_id", "product_id", name="uq_order_line_product"),
    )
    op.create_index(op.f("ix_order_lines_order_id"), "order_lines", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_lines_product_id"), "order_lines", ["product_id"], unique=False)
    op.create_table(
        "pick_tasks",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("assigned_user_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"], ["users.id"], name=op.f("fk_pick_tasks_assigned_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_pick_tasks_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], name=op.f("fk_pick_tasks_warehouse_id_warehouses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pick_tasks")),
    )
    op.create_index(op.f("ix_pick_tasks_order_id"), "pick_tasks", ["order_id"], unique=False)
    op.create_index(op.f("ix_pick_tasks_status"), "pick_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_pick_tasks_warehouse_id"), "pick_tasks", ["warehouse_id"], unique=False
    )
    op.create_index(
        "ix_pick_tasks_wh_status", "pick_tasks", ["warehouse_id", "status"], unique=False
    )
    op.create_table(
        "shipments",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("carrier", sa.String(length=50), nullable=False),
        sa.Column("service_level", sa.String(length=50), nullable=False),
        sa.Column("tracking_number", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "shipped_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_shipments_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], name=op.f("fk_shipments_warehouse_id_warehouses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipments")),
        sa.UniqueConstraint("tracking_number", name="uq_shipment_tracking"),
    )
    op.create_index(op.f("ix_shipments_order_id"), "shipments", ["order_id"], unique=False)
    op.create_index(op.f("ix_shipments_status"), "shipments", ["status"], unique=False)
    op.create_index(
        op.f("ix_shipments_tracking_number"), "shipments", ["tracking_number"], unique=True
    )
    op.create_index(op.f("ix_shipments_warehouse_id"), "shipments", ["warehouse_id"], unique=False)
    op.create_table(
        "inventory_reservations",
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "reserved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_inventory_reservations_order_line_id_order_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_reservations_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_reservations_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_reservations")),
    )
    op.create_index(
        op.f("ix_inventory_reservations_order_line_id"),
        "inventory_reservations",
        ["order_line_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_product_id"),
        "inventory_reservations",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_status"),
        "inventory_reservations",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_warehouse_id"),
        "inventory_reservations",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "packages",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("shipment_id", sa.UUID(), nullable=True),
        sa.Column("box_type", sa.String(length=50), nullable=False),
        sa.Column("weight_lbs", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("length_in", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("width_in", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("height_in", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_packages_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_packages_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_packages")),
    )
    op.create_index(op.f("ix_packages_order_id"), "packages", ["order_id"], unique=False)
    op.create_index(op.f("ix_packages_shipment_id"), "packages", ["shipment_id"], unique=False)
    op.create_table(
        "pick_task_lines",
        sa.Column("pick_task_id", sa.UUID(), nullable=False),
        sa.Column("order_line_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("requested_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("picked_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("short_quantity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["warehouse_locations.id"],
            name=op.f("fk_pick_task_lines_location_id_warehouse_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["order_line_id"],
            ["order_lines.id"],
            name=op.f("fk_pick_task_lines_order_line_id_order_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["pick_task_id"],
            ["pick_tasks.id"],
            name=op.f("fk_pick_task_lines_pick_task_id_pick_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_pick_task_lines_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pick_task_lines")),
    )
    op.create_index(
        op.f("ix_pick_task_lines_pick_task_id"), "pick_task_lines", ["pick_task_id"], unique=False
    )
    op.create_table(
        "shipment_events",
        sa.Column("shipment_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("details", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["shipment_id"],
            ["shipments.id"],
            name=op.f("fk_shipment_events_shipment_id_shipments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipment_events")),
    )
    op.create_index(
        op.f("ix_shipment_events_shipment_id"), "shipment_events", ["shipment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shipment_events_shipment_id"), table_name="shipment_events")
    op.drop_table("shipment_events")
    op.drop_index(op.f("ix_pick_task_lines_pick_task_id"), table_name="pick_task_lines")
    op.drop_table("pick_task_lines")
    op.drop_index(op.f("ix_packages_shipment_id"), table_name="packages")
    op.drop_index(op.f("ix_packages_order_id"), table_name="packages")
    op.drop_table("packages")
    op.drop_index(
        op.f("ix_inventory_reservations_warehouse_id"), table_name="inventory_reservations"
    )
    op.drop_index(op.f("ix_inventory_reservations_status"), table_name="inventory_reservations")
    op.drop_index(
        op.f("ix_inventory_reservations_product_id"), table_name="inventory_reservations"
    )
    op.drop_index(
        op.f("ix_inventory_reservations_order_line_id"), table_name="inventory_reservations"
    )
    op.drop_table("inventory_reservations")
    op.drop_index(op.f("ix_shipments_warehouse_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_tracking_number"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_status"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_order_id"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index("ix_pick_tasks_wh_status", table_name="pick_tasks")
    op.drop_index(op.f("ix_pick_tasks_warehouse_id"), table_name="pick_tasks")
    op.drop_index(op.f("ix_pick_tasks_status"), table_name="pick_tasks")
    op.drop_index(op.f("ix_pick_tasks_order_id"), table_name="pick_tasks")
    op.drop_table("pick_tasks")
    op.drop_index(op.f("ix_order_lines_product_id"), table_name="order_lines")
    op.drop_index(op.f("ix_order_lines_order_id"), table_name="order_lines")
    op.drop_table("order_lines")
    op.drop_index("ix_orders_wh_status", table_name="orders")
    op.drop_index(op.f("ix_orders_warehouse_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_seller_order_number"), table_name="orders")
    op.drop_index(op.f("ix_orders_seller_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
