"""transfers_and_returns

Revision ID: 671b43c62846
Revises: 'c9a20c29ffff'
Create Date: 2026-08-13 16:03:25.300616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671b43c62846'
down_revision: Union[str, None] = 'c9a20c29ffff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('transfer_number', sa.String(length=100), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('origin_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('origin_warehouse_id != destination_warehouse_id', name=op.f('ck_transfers_ck_transfer_origin_diff_dest')),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_transfers_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_transfers_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], name=op.f('fk_transfers_destination_warehouse_id_warehouses')),
    sa.ForeignKeyConstraint(['origin_warehouse_id'], ['warehouses.id'], name=op.f('fk_transfers_origin_warehouse_id_warehouses')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_transfers_seller_id_sellers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers'))
    )
    op.create_index(op.f('ix_transfers_destination_warehouse_id'), 'transfers', ['destination_warehouse_id'], unique=False)
    op.create_index('ix_transfers_origin_dest', 'transfers', ['origin_warehouse_id', 'destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_transfers_origin_warehouse_id'), 'transfers', ['origin_warehouse_id'], unique=False)
    op.create_index(op.f('ix_transfers_seller_id'), 'transfers', ['seller_id'], unique=False)
    op.create_index('ix_transfers_seller_status', 'transfers', ['seller_id', 'status'], unique=False)
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_index(op.f('ix_transfers_transfer_number'), 'transfers', ['transfer_number'], unique=True)
    op.create_table('returns',
    sa.Column('return_number', sa.String(length=100), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('rma_number', sa.String(length=100), nullable=True),
    sa.Column('inbound_tracking_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_returns_order_id_orders')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_returns_seller_id_sellers')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_returns_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_returns'))
    )
    op.create_index(op.f('ix_returns_inbound_tracking_number'), 'returns', ['inbound_tracking_number'], unique=False)
    op.create_index(op.f('ix_returns_order_id'), 'returns', ['order_id'], unique=False)
    op.create_index(op.f('ix_returns_return_number'), 'returns', ['return_number'], unique=True)
    op.create_index(op.f('ix_returns_rma_number'), 'returns', ['rma_number'], unique=False)
    op.create_index(op.f('ix_returns_seller_id'), 'returns', ['seller_id'], unique=False)
    op.create_index('ix_returns_seller_status', 'returns', ['seller_id', 'status'], unique=False)
    op.create_index(op.f('ix_returns_status'), 'returns', ['status'], unique=False)
    op.create_index(op.f('ix_returns_warehouse_id'), 'returns', ['warehouse_id'], unique=False)
    op.create_index('ix_returns_wh_status', 'returns', ['warehouse_id', 'status'], unique=False)
    op.create_table('transfer_lines',
    sa.Column('transfer_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('approved_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dispatched_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_good_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_damaged_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('missing_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('overage_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_transfer_lines_product_id_products')),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_transfer_lines_transfer_id_transfers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_lines'))
    )
    op.create_index(op.f('ix_transfer_lines_product_id'), 'transfer_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_transfer_lines_transfer_id'), 'transfer_lines', ['transfer_id'], unique=False)
    op.create_table('return_lines',
    sa.Column('return_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('expected_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('inspection_notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_return_lines_product_id_products')),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], name=op.f('fk_return_lines_return_id_returns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_lines'))
    )
    op.create_index(op.f('ix_return_lines_product_id'), 'return_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_return_lines_return_id'), 'return_lines', ['return_id'], unique=False)
    op.create_table('return_dispositions',
    sa.Column('return_line_id', sa.UUID(), nullable=False),
    sa.Column('disposition_state', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('destination_location_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_location_id'], ['warehouse_locations.id'], name=op.f('fk_return_dispositions_destination_location_id_warehouse_locations')),
    sa.ForeignKeyConstraint(['return_line_id'], ['return_lines.id'], name=op.f('fk_return_dispositions_return_line_id_return_lines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_dispositions'))
    )
    op.create_index(op.f('ix_return_dispositions_disposition_state'), 'return_dispositions', ['disposition_state'], unique=False)
    op.create_index(op.f('ix_return_dispositions_return_line_id'), 'return_dispositions', ['return_line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_dispositions_return_line_id'), table_name='return_dispositions')
    op.drop_index(op.f('ix_return_dispositions_disposition_state'), table_name='return_dispositions')
    op.drop_table('return_dispositions')
    op.drop_index(op.f('ix_return_lines_return_id'), table_name='return_lines')
    op.drop_index(op.f('ix_return_lines_product_id'), table_name='return_lines')
    op.drop_table('return_lines')
    op.drop_index(op.f('ix_transfer_lines_transfer_id'), table_name='transfer_lines')
    op.drop_index(op.f('ix_transfer_lines_product_id'), table_name='transfer_lines')
    op.drop_table('transfer_lines')
    op.drop_index('ix_returns_wh_status', table_name='returns')
    op.drop_index(op.f('ix_returns_warehouse_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_status'), table_name='returns')
    op.drop_index('ix_returns_seller_status', table_name='returns')
    op.drop_index(op.f('ix_returns_seller_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_rma_number'), table_name='returns')
    op.drop_index(op.f('ix_returns_return_number'), table_name='returns')
    op.drop_index(op.f('ix_returns_order_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_inbound_tracking_number'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_transfers_transfer_number'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_index('ix_transfers_seller_status', table_name='transfers')
    op.drop_index(op.f('ix_transfers_seller_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_origin_warehouse_id'), table_name='transfers')
    op.drop_index('ix_transfers_origin_dest', table_name='transfers')
    op.drop_index(op.f('ix_transfers_destination_warehouse_id'), table_name='transfers')
    op.drop_table('transfers')
    # ### end Alembic commands ###
