/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MigrationRouteImport } from './routes/migration'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PickTasksRouteImport } from './routes/pick-tasks'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReceiptsIndexRouteImport } from './routes/receipts/index'
import { Route as ReceiptsIdRouteImport } from './routes/receipts/$id'
import { Route as ReturnsIndexRouteImport } from './routes/returns/index'
import { Route as ReturnsIdRouteImport } from './routes/returns/$id'
import { Route as TransfersIndexRouteImport } from './routes/transfers/index'
import { Route as TransfersIdRouteImport } from './routes/transfers/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationRoute = MigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PickTasksRoute = PickTasksRouteImport.update({
  id: '/pick-tasks',
  path: '/pick-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIndexRoute = ReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsIdRoute = ReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIndexRoute = ReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIdRoute = ReturnsIdRouteImport.update({
  id: '/returns/$id',
  path: '/returns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIdRoute = TransfersIdRouteImport.update({
  id: '/transfers/$id',
  path: '/transfers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/migration': typeof MigrationRoute
  '/orders': typeof OrdersRoute
  '/pick-tasks': typeof PickTasksRoute
  '/shipments': typeof ShipmentsRoute
  '/signup': typeof SignupRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/transfers/$id': typeof TransfersIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/migration': typeof MigrationRoute
  '/orders': typeof OrdersRoute
  '/pick-tasks': typeof PickTasksRoute
  '/shipments': typeof ShipmentsRoute
  '/signup': typeof SignupRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/transfers/$id': typeof TransfersIdRoute
  '/receipts': typeof ReceiptsIndexRoute
  '/returns': typeof ReturnsIndexRoute
  '/transfers': typeof TransfersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/migration': typeof MigrationRoute
  '/orders': typeof OrdersRoute
  '/pick-tasks': typeof PickTasksRoute
  '/shipments': typeof ShipmentsRoute
  '/signup': typeof SignupRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/transfers/$id': typeof TransfersIdRoute
  '/receipts/': typeof ReceiptsIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/inventory'
    | '/login'
    | '/migration'
    | '/orders'
    | '/pick-tasks'
    | '/shipments'
    | '/signup'
    | '/receipts/$id'
    | '/returns/$id'
    | '/transfers/$id'
    | '/receipts/'
    | '/returns/'
    | '/transfers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/inventory'
    | '/login'
    | '/migration'
    | '/orders'
    | '/pick-tasks'
    | '/shipments'
    | '/signup'
    | '/receipts/$id'
    | '/returns/$id'
    | '/transfers/$id'
    | '/receipts'
    | '/returns'
    | '/transfers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/inventory'
    | '/login'
    | '/migration'
    | '/orders'
    | '/pick-tasks'
    | '/shipments'
    | '/signup'
    | '/receipts/$id'
    | '/returns/$id'
    | '/transfers/$id'
    | '/receipts/'
    | '/returns/'
    | '/transfers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiAssistantRoute: typeof AiAssistantRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MigrationRoute: typeof MigrationRoute
  OrdersRoute: typeof OrdersRoute
  PickTasksRoute: typeof PickTasksRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SignupRoute: typeof SignupRoute
  ReceiptsIdRoute: typeof ReceiptsIdRoute
  ReturnsIdRoute: typeof ReturnsIdRoute
  TransfersIdRoute: typeof TransfersIdRoute
  ReceiptsIndexRoute: typeof ReceiptsIndexRoute
  ReturnsIndexRoute: typeof ReturnsIndexRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick-tasks': {
      id: '/pick-tasks'
      path: '/pick-tasks'
      fullPath: '/pick-tasks'
      preLoaderRoute: typeof PickTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/': {
      id: '/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof ReceiptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$id': {
      id: '/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ReceiptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/': {
      id: '/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof ReturnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/$id': {
      id: '/returns/$id'
      path: '/returns/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof ReturnsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/$id': {
      id: '/transfers/$id'
      path: '/transfers/$id'
      fullPath: '/transfers/$id'
      preLoaderRoute: typeof TransfersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiAssistantRoute: AiAssistantRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MigrationRoute: MigrationRoute,
  OrdersRoute: OrdersRoute,
  PickTasksRoute: PickTasksRoute,
  ShipmentsRoute: ShipmentsRoute,
  SignupRoute: SignupRoute,
  ReceiptsIdRoute: ReceiptsIdRoute,
  ReturnsIdRoute: ReturnsIdRoute,
  TransfersIdRoute: TransfersIdRoute,
  ReceiptsIndexRoute: ReceiptsIndexRoute,
  ReturnsIndexRoute: ReturnsIndexRoute,
  TransfersIndexRoute: TransfersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
